"""Initial migration

Revision ID: 2524fc6838c9
Revises: 
Create Date: 2025-11-28 22:51:28.595905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2524fc6838c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capability', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('intent', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('targeting', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_entry', schema=None) as batch_op:
        batch_op.drop_column('targeting')
        batch_op.drop_column('intent')
        batch_op.drop_column('capability')

    # ### end Alembic commands ###
